[package]
name = "nn"
version = "0.1.0"
authors = ["Dario Biscevic <dario.biscevic03@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
ansi_term = "*"